#!/usr/bin/env python3
"""
discogs-cleaner — rename.py

Applies folder renames generated by the discogs-cleaner web UI.

Usage:
    python rename.py --dry-run                      # preview only, no changes
    python rename.py --path "D:/Music/Labels"       # apply in a specific directory
    python rename.py --path "." --input results.json

The rename list is either:
  - Pasted directly into RENAMES below (copy from the web UI), or
  - Loaded from a JSON file exported by the web UI (--input results.json)
"""

import os
import sys
import json
import argparse

# Paste your renames here, or use --input to load from exported JSON
RENAMES = [
    # ("old folder name", "new folder name"),
    # ("(1997) Delerium - Karma", "[CARD001] Delerium - Karma (1997)"),
]


def load_from_json(path):
    with open(path, "r", encoding="utf-8") as f:
        data = json.load(f)
    return [
        (r["original"], r["newName"])
        for r in data
        if r.get("status") == "found" and r["original"] != r["newName"]
    ]


def sanitize_name(name):
    """Remove characters not allowed in Windows/macOS/Linux folder names."""
    invalid = r'<>:"/\|?*'
    for ch in invalid:
        name = name.replace(ch, "")
    return name.strip()


def main():
    parser = argparse.ArgumentParser(
        description="Rename music folders using Discogs metadata from discogs-cleaner."
    )
    parser.add_argument(
        "--path",
        default=".",
        help="Root directory containing the folders to rename (default: current dir)",
    )
    parser.add_argument(
        "--input",
        default=None,
        help="Path to JSON file exported from discogs-cleaner web UI",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Preview renames without making any changes",
    )
    args = parser.parse_args()

    root = os.path.abspath(args.path)
    if not os.path.isdir(root):
        print(f"ERROR: Directory not found: {root}")
        sys.exit(1)

    if args.input:
        try:
            renames = load_from_json(args.input)
            print(f"Loaded {len(renames)} renames from {args.input}")
        except Exception as e:
            print(f"ERROR loading JSON: {e}")
            sys.exit(1)
    else:
        renames = RENAMES
        if not renames:
            print("No renames defined. Paste pairs into RENAMES or use --input results.json")
            sys.exit(0)

    print(f"\nRoot:  {root}")
    print(f"Mode:  {'DRY RUN (no changes will be made)' if args.dry_run else 'LIVE'}")
    print(f"Total: {len(renames)} renames\n")
    print("-" * 60)

    ok, skip, err = 0, 0, 0

    for old_name, new_name in renames:
        new_name_safe = sanitize_name(new_name)
        old_path = os.path.join(root, old_name)
        new_path = os.path.join(root, new_name_safe)

        if not os.path.exists(old_path):
            print(f"  [SKIP] not on disk:  {old_name}")
            skip += 1
            continue

        if os.path.exists(new_path) and os.path.abspath(old_path) != os.path.abspath(new_path):
            print(f"  [SKIP] conflict:     {old_name}")
            print(f"         target exists: {new_name_safe}")
            skip += 1
            continue

        if old_name == new_name_safe:
            print(f"  [SKIP] unchanged:    {old_name}")
            skip += 1
            continue

        print(f"  [{'DRY' if args.dry_run else 'OK'}]  {old_name}")
        print(f"         → {new_name_safe}")

        if not args.dry_run:
            try:
                os.rename(old_path, new_path)
                ok += 1
            except OSError as e:
                print(f"  [ERR]  {e}")
                err += 1
        else:
            ok += 1

    print("-" * 60)
    print(f"\nDone.  {ok} renamed · {skip} skipped · {err} errors")
    if args.dry_run:
        print("Run without --dry-run to apply changes.")


if __name__ == "__main__":
    main()
